version: '3'
services:
    api1:
      build: ./../todo-api
      ports:
        - "9001:9000"
    api2:
      build: ./../todo-api
      ports:
        - "9002:9000"
    loadbalancer:
      build: ./
      ports:
        - "3000:80"
      depends_on:
        - api1
        - api2